# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rare/protos/decoder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rare.protos.rnn_cell_pb2
import rare.protos.embedding_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rare/protos/decoder.proto',
  package='rare.protos',
  serialized_pb=_b('\n\x19rare/protos/decoder.proto\x12\x0brare.protos\x1a\x1arare/protos/rnn_cell.proto\x1a\x1brare/protos/embedding.proto\"V\n\x07\x44\x65\x63oder\x12:\n\x11\x61ttention_decoder\x18\x01 \x01(\x0b\x32\x1d.rare.protos.AttentionDecoderH\x00\x42\x0f\n\rdecoder_oneof\"\xb5\x01\n\x10\x41ttentionDecoder\x12&\n\x08rnn_cell\x18\x01 \x01(\x0b\x32\x14.rare.protos.RnnCell\x12 \n\x13num_attention_units\x18\x02 \x01(\r:\x03\x31\x32\x38\x12%\n\x1a\x61ttention_conv_kernel_size\x18\x03 \x01(\r:\x01\x35\x12\x30\n\x10output_embedding\x18\x04 \x01(\x0b\x32\x16.rare.protos.Embedding')
  ,
  dependencies=[rare.protos.rnn_cell_pb2.DESCRIPTOR,rare.protos.embedding_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DECODER = _descriptor.Descriptor(
  name='Decoder',
  full_name='rare.protos.Decoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attention_decoder', full_name='rare.protos.Decoder.attention_decoder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='decoder_oneof', full_name='rare.protos.Decoder.decoder_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=99,
  serialized_end=185,
)


_ATTENTIONDECODER = _descriptor.Descriptor(
  name='AttentionDecoder',
  full_name='rare.protos.AttentionDecoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rnn_cell', full_name='rare.protos.AttentionDecoder.rnn_cell', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_attention_units', full_name='rare.protos.AttentionDecoder.num_attention_units', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=128,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attention_conv_kernel_size', full_name='rare.protos.AttentionDecoder.attention_conv_kernel_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_embedding', full_name='rare.protos.AttentionDecoder.output_embedding', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=369,
)

_DECODER.fields_by_name['attention_decoder'].message_type = _ATTENTIONDECODER
_DECODER.oneofs_by_name['decoder_oneof'].fields.append(
  _DECODER.fields_by_name['attention_decoder'])
_DECODER.fields_by_name['attention_decoder'].containing_oneof = _DECODER.oneofs_by_name['decoder_oneof']
_ATTENTIONDECODER.fields_by_name['rnn_cell'].message_type = rare.protos.rnn_cell_pb2._RNNCELL
_ATTENTIONDECODER.fields_by_name['output_embedding'].message_type = rare.protos.embedding_pb2._EMBEDDING
DESCRIPTOR.message_types_by_name['Decoder'] = _DECODER
DESCRIPTOR.message_types_by_name['AttentionDecoder'] = _ATTENTIONDECODER

Decoder = _reflection.GeneratedProtocolMessageType('Decoder', (_message.Message,), dict(
  DESCRIPTOR = _DECODER,
  __module__ = 'rare.protos.decoder_pb2'
  # @@protoc_insertion_point(class_scope:rare.protos.Decoder)
  ))
_sym_db.RegisterMessage(Decoder)

AttentionDecoder = _reflection.GeneratedProtocolMessageType('AttentionDecoder', (_message.Message,), dict(
  DESCRIPTOR = _ATTENTIONDECODER,
  __module__ = 'rare.protos.decoder_pb2'
  # @@protoc_insertion_point(class_scope:rare.protos.AttentionDecoder)
  ))
_sym_db.RegisterMessage(AttentionDecoder)


# @@protoc_insertion_point(module_scope)
