# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rare/protos/embedding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rare/protos/embedding.proto',
  package='rare.protos',
  serialized_pb=_b('\n\x1brare/protos/embedding.proto\x12\x0brare.protos\"Y\n\tEmbedding\x12\x39\n\x11one_hot_embedding\x18\x01 \x01(\x0b\x32\x1c.rare.protos.OneHotEmbeddingH\x00\x42\x11\n\x0f\x65mbedding_oneof\"\x11\n\x0fOneHotEmbedding')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EMBEDDING = _descriptor.Descriptor(
  name='Embedding',
  full_name='rare.protos.Embedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='one_hot_embedding', full_name='rare.protos.Embedding.one_hot_embedding', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='embedding_oneof', full_name='rare.protos.Embedding.embedding_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=44,
  serialized_end=133,
)


_ONEHOTEMBEDDING = _descriptor.Descriptor(
  name='OneHotEmbedding',
  full_name='rare.protos.OneHotEmbedding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=152,
)

_EMBEDDING.fields_by_name['one_hot_embedding'].message_type = _ONEHOTEMBEDDING
_EMBEDDING.oneofs_by_name['embedding_oneof'].fields.append(
  _EMBEDDING.fields_by_name['one_hot_embedding'])
_EMBEDDING.fields_by_name['one_hot_embedding'].containing_oneof = _EMBEDDING.oneofs_by_name['embedding_oneof']
DESCRIPTOR.message_types_by_name['Embedding'] = _EMBEDDING
DESCRIPTOR.message_types_by_name['OneHotEmbedding'] = _ONEHOTEMBEDDING

Embedding = _reflection.GeneratedProtocolMessageType('Embedding', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDING,
  __module__ = 'rare.protos.embedding_pb2'
  # @@protoc_insertion_point(class_scope:rare.protos.Embedding)
  ))
_sym_db.RegisterMessage(Embedding)

OneHotEmbedding = _reflection.GeneratedProtocolMessageType('OneHotEmbedding', (_message.Message,), dict(
  DESCRIPTOR = _ONEHOTEMBEDDING,
  __module__ = 'rare.protos.embedding_pb2'
  # @@protoc_insertion_point(class_scope:rare.protos.OneHotEmbedding)
  ))
_sym_db.RegisterMessage(OneHotEmbedding)


# @@protoc_insertion_point(module_scope)
