# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rare/protos/feature_extractor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rare/protos/feature_extractor.proto',
  package='rare.protos',
  serialized_pb=_b('\n#rare/protos/feature_extractor.proto\x12\x0brare.protos\"z\n\x10\x46\x65\x61tureExtractor\x12K\n\x1a\x62\x61seline_feature_extractor\x18\x01 \x01(\x0b\x32%.rare.protos.BaselineFeatureExtractorH\x00\x42\x19\n\x17\x66\x65\x61ture_extractor_oneof\"\x1a\n\x18\x42\x61selineFeatureExtractor')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEATUREEXTRACTOR = _descriptor.Descriptor(
  name='FeatureExtractor',
  full_name='rare.protos.FeatureExtractor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baseline_feature_extractor', full_name='rare.protos.FeatureExtractor.baseline_feature_extractor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='feature_extractor_oneof', full_name='rare.protos.FeatureExtractor.feature_extractor_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=52,
  serialized_end=174,
)


_BASELINEFEATUREEXTRACTOR = _descriptor.Descriptor(
  name='BaselineFeatureExtractor',
  full_name='rare.protos.BaselineFeatureExtractor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=202,
)

_FEATUREEXTRACTOR.fields_by_name['baseline_feature_extractor'].message_type = _BASELINEFEATUREEXTRACTOR
_FEATUREEXTRACTOR.oneofs_by_name['feature_extractor_oneof'].fields.append(
  _FEATUREEXTRACTOR.fields_by_name['baseline_feature_extractor'])
_FEATUREEXTRACTOR.fields_by_name['baseline_feature_extractor'].containing_oneof = _FEATUREEXTRACTOR.oneofs_by_name['feature_extractor_oneof']
DESCRIPTOR.message_types_by_name['FeatureExtractor'] = _FEATUREEXTRACTOR
DESCRIPTOR.message_types_by_name['BaselineFeatureExtractor'] = _BASELINEFEATUREEXTRACTOR

FeatureExtractor = _reflection.GeneratedProtocolMessageType('FeatureExtractor', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREEXTRACTOR,
  __module__ = 'rare.protos.feature_extractor_pb2'
  # @@protoc_insertion_point(class_scope:rare.protos.FeatureExtractor)
  ))
_sym_db.RegisterMessage(FeatureExtractor)

BaselineFeatureExtractor = _reflection.GeneratedProtocolMessageType('BaselineFeatureExtractor', (_message.Message,), dict(
  DESCRIPTOR = _BASELINEFEATUREEXTRACTOR,
  __module__ = 'rare.protos.feature_extractor_pb2'
  # @@protoc_insertion_point(class_scope:rare.protos.BaselineFeatureExtractor)
  ))
_sym_db.RegisterMessage(BaselineFeatureExtractor)


# @@protoc_insertion_point(module_scope)
